# ! Warning !
# This file is used for local development only

services:
  db:
    image: mysql
    restart: "no"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: Ascent
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
