[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm run prisma:generate', 'pnpm build']

[start]
cmd = 'pnpm run prisma:migrate-prod && node build/index.js'
